#45306552 TB-key
development:
  KEY_ID: "AKIAIE4MDNHYCTXWAJTQ"
  ACCESS_KEY: "8YcZRZ1J5I3/huQ+JPHF3jW3DaeLpmQe+jYzhmxW"
production:
  KEY_ID: "AKIAIE4MDNHYCTXWAJTQ"
  ACCESS_KEY: "8YcZRZ1J5I3/huQ+JPHF3jW3DaeLpmQe+jYzhmxW"
